### PR TITLE
simplify MMR index arithmetic

### PR DESCRIPTION
**Pull request by jan-ferdinand**
Thank you, OEIS: [A005187](https://oeis.org/A005187).

### CODE REVIEW

**Comment by Sword-Smith** [comment]
If `non_leaf_nodes_left` is no longer used in `leaf_index_to_node_index`, I think `non_leaf_nodes_left` can be removed entirely.

**Review by Sword-Smith — CHANGES_REQUESTED** [review]
If non_leaf_nodes_left is no longer used in leaf_index_to_node_index, I think non_leaf_nodes_left can be removed entirely.

**Comment by jan-ferdinand** [comment]
Good catch. :+1:

**Comment by Sword-Smith** [comment]
Some of the code is complicated by the `node_index` being zero-indexed instead of one-indexed. Would it be worth seeing what the effects of zero-indexing `node_index` would result in? If you want to give that a try, please do. If not, I'll have a look at it.

**Review by Sword-Smith — APPROVED** [review]
LGTM

**Pull request merged**
