### PR TITLE
switch to get-size2

### PR DESCRIPTION
**Pull request by bircni**

### CODE REVIEW

**Comment by aszepieniec** [comment]
(Why) would you say that getsize2 is superior to getsize?

**Comment by bircni** [comment]
https://github.com/DKerp/get-size/issues/22

**Comment by Sword-Smith** [comment]
@bircni Thanks for the PR! This seems like a good upgrade, that we should include in the 0.43 version and downstream.

**Comment by bircni** [comment]
would be nice!

**Comment by bircni** [comment]
fixed the merge conflict

**Comment by Sword-Smith** [comment]
Thanks. Merged.

**Pull request merged**
