### PR TITLE
ignore zero-coefficients for computing polynomials total degree

### LINKED ISSUE #50: Error in `MPolynomial::degree`
This method seems to wrongly count terms whose coefficient is zero towards the degree of a multivariate polynomial. It shouldn't.

https://github.com/Neptune-Crypto/twenty-first/blob/master/twenty-first/src/shared_math/mpolynomial.rs#L1057-L1071

### PR DESCRIPTION
**Pull request by jan-ferdinand**
Fix #50.

### CODE REVIEW

**Comment by Sword-Smith** [comment]
Nice. That was fast :)

**Comment by Sword-Smith** [comment]
LGTM

**Review by Sword-Smith — APPROVED** [review]
Good tests as always :)

**Comment by jan-ferdinand** [comment]
> Good tests as always :)

Could be better, but I couldn't think of anything fast enough. :relieved:

**Comment by Sword-Smith** [comment]
> > Good tests as always :)
> 
> Could be better, but I couldn't think of anything fast enough. 😌

There are a lot of tests that touch `degree` for mpols already. No need to exaggerate for this cornercase.

**Pull request merged**
