### PR TITLE
typo-Update README.md

### PR DESCRIPTION
**Pull request by romashka-btc**
# Fix: Corrected typo in documentation file

## Changes
- `README.md:39`: "degredation" corrected to "degradation".

## Purpose
- Improved documentation accuracy and ensured professionalism.

### CODE REVIEW

**Comment by romashka-btc** [comment]
> Member

so you do not merge it ?

**Comment by jan-ferdinand** [comment]
> so you do not merge it ?

That is correct.

**Comment by romashka-btc** [comment]
> > so you do not merge it ?
> 
> That is correct.

(

**Comment by romashka-btc** [comment]
> > so you do not merge it ?
> 
> That is correct.

but this is not honest to community ! 

i wish you all the best

**Pull request closed without merging**
